import { nanoid } from 'nanoid';

const config = {
    totalMoney: 100000000000,
    marketItems: [
      {
        id: nanoid(),
        name: "Big Mac",
        photo: "https://neal.fun/spend/images/big-mac.jpg",
        price: 2,
      },
      {
        id: nanoid(),
        name: "Flip Flops",
        photo: "https://neal.fun/spend/images/flip-flops.jpg",
        price: 3,
      },
      {
        id: nanoid(),
        name: "Coca-Cola Pack",
        photo: "https://neal.fun/spend/images/coca-cola-pack.jpg",
        price: 5,
      },
      {
        id: nanoid(),
        name: "Movie Ticket",
        photo: "https://neal.fun/spend/images/movie-ticket.jpg",
        price: 12,
      },
      {
        id: nanoid(),
        name: "Book",
        photo: "https://neal.fun/spend/images/book.jpg",
        price: 15,
      },
      {
        id: nanoid(),
        name: "Lobster Dinner",
        photo: "https://neal.fun/spend/images/lobster-dinner.jpg",
        price: 45,
      },
      {
        id: nanoid(),
        name: "Video Game",
        photo: "https://neal.fun/spend/images/video-game.jpg",
        price: 60,
      },
      {
        id: nanoid(),
        name: "Amazon Echo",
        photo: "https://neal.fun/spend/images/amazon-echo.jpg",
        price: 99,
      },
      {
        id: nanoid(),
        name: "Year of Netflix",
        photo: "https://neal.fun/spend/images/year-of-netflix.jpg",
        price: 100,
      },
      {
        id: nanoid(),
        name: "Air Jordans",
        photo: "https://neal.fun/spend/images/air-jordans.jpg",
        price: 125,
      },
      {
        id: nanoid(),
        name: "Airpods",
        photo: "https://neal.fun/spend/images/airpods.jpg",
        price: 199,
      },
      {
        id: nanoid(),
        name: "Gaming Console",
        photo: "https://neal.fun/spend/images/gaming-console.jpg",
        price: 299,
      },
      {
        id: nanoid(),
        name: "Drone",
        photo: "https://neal.fun/spend/images/drone.jpg",
        price: 350,
      },
      {
        id: nanoid(),
        name: "Smartphone",
        photo: "https://neal.fun/spend/images/smartphone.jpg",
        price: 699,
      },
      {
        id: nanoid(),
        name: "Bike",
        photo: "https://neal.fun/spend/images/bike.jpg",
        price: 800,
      },
      {
        id: nanoid(),
        name: "Kitten",
        photo: "https://neal.fun/spend/images/kitten.jpg",
        price: 1500,
      },
      {
        id: nanoid(),
        name: "Puppy",
        photo: "https://neal.fun/spend/images/puppy.jpg",
        price: 1500,
      },
      {
        id: nanoid(),
        name: "Auto Rickshaw",
        photo: "https://neal.fun/spend/images/auto-rickshaw.jpg",
        price: 2300,
      },
      {
        id: nanoid(),
        name: "Horse",
        photo: "https://neal.fun/spend/images/horse.jpg",
        price: 2500,
      },
      {
        id: nanoid(),
        name: "Acre of Farmland",
        photo: "https://neal.fun/spend/images/acre-of-farmland.jpg",
        price: 3000,
      },
      {
        id: nanoid(),
        name: "Designer Handbag",
        photo: "https://neal.fun/spend/images/designer-handbag.jpg",
        price: 5500,
      },
      {
        id: nanoid(),
        name: "Hot Tub",
        photo: "https://neal.fun/spend/images/hot-tub.jpg",
        price: 6000,
      },
      {
        id: nanoid(),
        name: "Luxury Wine",
        photo: "https://neal.fun/spend/images/luxury-wine.jpg",
        price: 7000,
      },
      {
        id: nanoid(),
        name: "Diamond Ring",
        photo: "https://neal.fun/spend/images/diamond-ring.jpg",
        price: 10000,
      },
      {
        id: nanoid(),
        name: "Jet Ski",
        photo: "https://neal.fun/spend/images/jet-ski.jpg",
        price: 12000,
      },
      {
        id: nanoid(),
        name: "Rolex",
        photo: "https://neal.fun/spend/images/rolex.jpg",
        price: 15000,
      },
      {
        id: nanoid(),
        name: "Ford F-150",
        photo: "https://neal.fun/spend/images/ford-f-150.jpg",
        price: 30000,
      },
      {
        id: nanoid(),
        name: "Tesla",
        photo: "https://neal.fun/spend/images/tesla.jpg",
        price: 75000,
      },
      {
        id: nanoid(),
        name: "Monster Truck",
        photo: "https://neal.fun/spend/images/monster-truck.jpg",
        price: 150000,
      },
      {
        id: nanoid(),
        name: "Ferrari",
        photo: "https://neal.fun/spend/images/ferrari.jpg",
        price: 250000,
      },
      {
        id: nanoid(),
        name: "Single Family Home",
        photo: "https://neal.fun/spend/images/single-family-home.jpg",
        price: 300000,
      },
      {
        id: nanoid(),
        name: "Gold Bar",
        photo: "https://neal.fun/spend/images/gold-bar.jpg",
        price: 700000,
      },
      {
        id: nanoid(),
        name: "McDonalds Franchise",
        photo: "https://neal.fun/spend/images/mcdonalds-franchise.jpg",
        price: 1500000,
      },
      {
        id: nanoid(),
        name: "Superbowl Ad",
        photo: "https://neal.fun/spend/images/superbowl-ad.jpg",
        price: 5250000,
      },
      {
        id: nanoid(),
        name: "Yacht",
        photo: "https://neal.fun/spend/images/yacht.jpg",
        price: 7500000,
      },
      {
        id: nanoid(),
        name: "M1 Abrams",
        photo: "https://neal.fun/spend/images/m1-abrams.jpg",
        price: 8000000,
      },
      {
        id: nanoid(),
        name: "Formula 1 Car",
        photo: "https://neal.fun/spend/images/formula-1-car.jpg",
        price: 15000000,
      },
      {
        id: nanoid(),
        name: "Apache Helicopter",
        photo: "https://neal.fun/spend/images/apache-helicopter.jpg",
        price: 31000000,
      },
      {
        id: nanoid(),
        name: "Mansion",
        photo: "https://neal.fun/spend/images/mansion.jpg",
        price: 45000000,
      },
      {
        id: nanoid(),
        name: "Make a Movie",
        photo: "https://neal.fun/spend/images/make-a-movie.jpg",
        price: 100000000,
      },
      {
        id: nanoid(),
        name: "Boeing 747",
        photo: "https://neal.fun/spend/images/boeing-747.jpg",
        price: 148000000,
      },
      {
        id: nanoid(),
        name: "Mona Lisa",
        photo: "https://neal.fun/spend/images/mona-lisa.jpg",
        price: 780000000,
      },
      {
        id: nanoid(),
        name: "Skyscraper",
        photo: "https://neal.fun/spend/images/skyscraper.jpg",
        price: 850000000,
      },
      {
        id: nanoid(),
        name: "Cruise Ship",
        photo: "https://neal.fun/spend/images/cruise-ship.jpg",
        price: 930000000,
      },
      {
        id: nanoid(),
        name: "NBA Team",
        photo: "https://neal.fun/spend/images/nba-team.jpg",
        price: 2120000000,
      },
    ],
  };
  
  export default config;
  